name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

jobs:
  frontend-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        working-directory: frontend
        run: npm install

      - name: Rodar linter
        working-directory: frontend
        run: npm run lint || echo "Lint opcional, configure conforme necessidade"

      - name: Build
        working-directory: frontend
        run: npm run build
